### PR TITLE
[hacktoberfest] - creating unit tests for BooleanParser class

### PR DESCRIPTION
**Pull request by tminussi**
Hello @JPDSousa. I have gone ahead and created unit tests for BooleanParser class. If you like the changes and approve them, please let me know and I will create tests for the other parsers as well.

Thanks and looking forward to contributing more!

### CODE REVIEW

**Comment by JPDSousa** [comment]
Hi @tminussi. Thanks for contributing! Everything seems awesome ;) I'll accept it right away! I'm glad you had the courage to dive into the parser's code.

Some minor notes:
 - I'been using the [Preconditions](https://github.com/google/guava/wiki/PreconditionsExplained) library from Guava to handle null values on arguments. It's not a big deal (it's not a "deal" at all), i just didn't knew your method (java Objects), so i'm sharing mine (feel to continue using your method though).
 - The whole parser package is quite mature at this point, but i often find minor bugs (e.g. cases that weren't considered, missing features, design problems, etc.), so if you run into something like this feel free to discuss and suggest! ;)

**Comment by tminussi** [comment]
This is awesome.

Thanks for the pointing out the minor notes.

I will surely contribute more and look out for scenarios that were not predicted at first.

You have a good day,

Thales

**Comment by tminussi** [comment]
@JPDSousa I have created some more unit tests. Now for ByteParser which is a quite complex and important class to the project I think. 

It is not fully covered but most of it is.

Can I keep using the issue (#25) to add further commits?

Thanks for letting me contribute to your project.

Thales

**Comment by JPDSousa** [comment]
@tminussi Sure, just keep using the issue. I decided to create a single issue for all the unity testing instead of creating separate issues with different parts of the project. I'm reviewing you're tests on the ByteParser, i'll merge the pr in a moment!

**Pull request merged**
